version: '3'

services:
  kafka:
    image: 'apache/kafka:latest'
    networks:
      - local-network
    ports:
      - '9092:9092'
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true

  kafkorama-gateway:
    image: kafkorama/kafkorama-gateway:latest
    restart: always
    ports:
      - "8800:8800"
    depends_on:
      - kafka
    networks:
      - local-network
    volumes:
      - ./gateway/addons/authorization-hub/configuration.properties:/migratorydata/addons/authorization-hub/configuration.properties
      - ./gateway/migratorydata.conf:/migratorydata/migratorydata.conf

  kafkorama-portal:
    image: kafkorama/kafkorama-portal:latest
    restart: always
    depends_on:
      - kafkorama-gateway
    ports:
      - "8080:8080"
    networks:
      - local-network
    volumes:
      - ./data/db:/hub/data
      - ./portal/extension.conf:/hub/extension.conf

  demo-stocks:
    image: kafkorama/demo-stocks:latest
    restart: always
    depends_on:
      - kafkorama-gateway
    networks:
      - local-network
    environment:
      - SERVER=kafkorama-gateway:8800
      - TOKEN=eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJkNzcyMTUiLCJwZXJtaXNzaW9ucyI6eyJhbGwiOlsiL2thZmtvcmFtYS9kZW1vLyoiXX0sImFwcCI6ImthZmtvcmFtYS1hcHAtaWQiLCJpYXQiOjE3NDU5MTY2OTgsImV4cCI6MTkwMzcwMTMyOH0.JBomOnpTUXJqwP04leBaHAvc1D5W75TV1vq8pHWPHOs
      - GET_SYMBOLS=/kafkorama/demo/stocks/symbols
      - TOPICS=/kafkorama/demo/stocks/AWERQ,/kafkorama/demo/stocks/WERZF,/kafkorama/demo/stocks/QWZAF,/kafkorama/demo/stocks/TEYDF,/kafkorama/demo/stocks/TYUII,/kafkorama/demo/stocks/XCVSD,/kafkorama/demo/stocks/POUVB,/kafkorama/demo/stocks/TYEWD,/kafkorama/demo/stocks/WYWUI

  demo-traffic:
    image: kafkorama/demo-traffic:latest
    restart: always
    depends_on:
      - kafkorama-gateway
    networks:
      - local-network
    environment:
      - SERVER=kafkorama-gateway:8800
      - TOKEN=eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJkNzcyMTUiLCJwZXJtaXNzaW9ucyI6eyJhbGwiOlsiL2thZmtvcmFtYS9kZW1vLyoiXX0sImFwcCI6ImthZmtvcmFtYS1hcHAtaWQiLCJpYXQiOjE3NDU5MTY2OTgsImV4cCI6MTkwMzcwMTMyOH0.JBomOnpTUXJqwP04leBaHAvc1D5W75TV1vq8pHWPHOs
      - SUBJECT=/kafkorama/demo/traffic/brussels

  demo-cryptocurrency:
    image: kafkorama/demo-cryptocurrency:latest
    restart: always
    depends_on:
      - kafkorama-gateway
    networks:
      - local-network
    environment:
      - SERVER=kafkorama-gateway:8800
      - TOKEN=eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJkNzcyMTUiLCJwZXJtaXNzaW9ucyI6eyJhbGwiOlsiL2thZmtvcmFtYS9kZW1vLyoiXX0sImFwcCI6ImthZmtvcmFtYS1hcHAtaWQiLCJpYXQiOjE3NDU5MTY2OTgsImV4cCI6MTkwMzcwMTMyOH0.JBomOnpTUXJqwP04leBaHAvc1D5W75TV1vq8pHWPHOs
      - SUBJECT=/kafkorama/demo/cryptocurrency/rates

  demo-parking:
    image: kafkorama/demo-parking:latest
    restart: always
    depends_on:
      - kafkorama-gateway
    networks:
      - local-network
    environment:
      - SERVER=kafkorama-gateway:8800
      - TOKEN=eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJkNzcyMTUiLCJwZXJtaXNzaW9ucyI6eyJhbGwiOlsiL2thZmtvcmFtYS9kZW1vLyoiXX0sImFwcCI6ImthZmtvcmFtYS1hcHAtaWQiLCJpYXQiOjE3NDU5MTY2OTgsImV4cCI6MTkwMzcwMTMyOH0.JBomOnpTUXJqwP04leBaHAvc1D5W75TV1vq8pHWPHOs
      - SUBJECT=/kafkorama/demo/parking

  demo-seismic:
    image: kafkorama/demo-seismic:latest
    restart: always
    depends_on:
      - kafkorama-gateway
    networks:
      - local-network
    environment:
      - SERVER=kafkorama-gateway:8800
      - TOKEN=eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJkNzcyMTUiLCJwZXJtaXNzaW9ucyI6eyJhbGwiOlsiL2thZmtvcmFtYS9kZW1vLyoiXX0sImFwcCI6ImthZmtvcmFtYS1hcHAtaWQiLCJpYXQiOjE3NDU5MTY2OTgsImV4cCI6MTkwMzcwMTMyOH0.JBomOnpTUXJqwP04leBaHAvc1D5W75TV1vq8pHWPHOs
      - SUBJECT=/kafkorama/demo/seismic/info

networks:
  local-network:
    driver: bridge

