
memory=512MB

log.folder=logs

portal.gateway.access.password=my-password
portal.listen.ip=0.0.0.0
portal.listen.port=8080
portal.admin.email=admin@admin.com
portal.admin.password=password
portal.admin.organization=kafkorama
portal.verifyEmail=false

# the server address used by the web console to connect clients to MigratoryData cluster.
### params related to Kafkorama Gateway
gateway.servers=127.0.0.1:8800
gateway.tls.enabled=false
gateway.auth.signature.type=hmac
gateway.auth.signature.hmac.secret=He39zDQW7RdkOcxe3L9qvoSQ/ef40BG6Ro4hrHDjE+U=

# default user
admin.email=admin@admin.com
admin.password=password
admin.organization=kafkorama

demo.apis = true
demo.topic = demo
demo.bootstrap.servers = kafka:9092
demo.key = g4hD1hIgPDpcD//R22XFWXVEgt38Z5KI3QS9jHlnLnk=

db.name=./data/kafkorama-portal.db
db.type=sqlite
db.driver.classpath=org.sqlite.JDBC
db.user=root
db.password=
db.ip=127.0.0.1
db.port=3306
db.ssl=false
