LicenseKey = zczuvikp41d2jb2o7j6n

Memory = 128MB

Listen = *:8800

LogLevel=INFO
LogRotateLimit = 10 MB
LogFolder = logs

DocumentRoot = html

Entitlement=PORTAL
Portal.Url = http://kafkorama-portal:8080
Portal.Password = my-password

Rest.Enable = true

Stats.LogInterval=5
Stats.PrettyPrint=true
